### ISSUE TITLE
直接打包源仓库以实现本仓库语言包的更新

### ISSUE THREAD

**Issue by Tryanks** [zkitefly/TranslationPackMirror#4]
使用github-action可以做到此行为，如果有需要，我可以提供帮助。

这是为了缓解由于镜像站本身也参与服务器下载请求，造成的服务器带宽/流量费用压力问题。

尽管已经把下载请求时间放在凌晨3/4/5的带宽低峰期，但造成的流量消耗依旧可观。

**Comment by zkitefly** [comment]
那为什么不直接 https://github.com/zkitefly/TranslationPackMirror/tree/CFPAOrg/Minecraft-Mod-Language-Package

**Comment by Tryanks** [comment]
> 那为什么不直接 https://github.com/zkitefly/TranslationPackMirror/tree/CFPAOrg/Minecraft-Mod-Language-Package

不太理解您直接放个分支链接的含义所在。我观察了下仓库内容似乎目前没有区别。

**Comment by zkitefly** [comment]
这个是我做了一半的东西，直接读取 CFPAOrg/Minecraft-Mod-Language-Package 最新 releases ，但因为 github-action 能够重新访问没糖的服务器，我就不做了。

https://github.com/zkitefly/TranslationPackMirror/compare/main...CFPAOrg/Minecraft-Mod-Language-Package

我不太能接受自己打包，这样就不是官方的东西了，怕有人胡思乱想（即使编译文件一致）

**Comment by zkitefly** [comment]
github-action只会在凌晨三四五点去运行检查

检查规则就是下载 http://downloader1.meitangdehulu.com:22943/ 下载 index.html （这个不大吧，就几kb）校验md5，如果校验不通过，才进行拉取更新，通过就跳过拉取。这消耗的流量够小的了吧

![image](https://user-images.githubusercontent.com/64117916/212582713-971ad5b8-913c-4dda-a979-f2fff76ef3fb.png)

**Comment by Tryanks** [comment]
> 直接读取 CFPAOrg/Minecraft-Mod-Language-Package 最新 releases 。

我个人是更希望把它做完，主要原因在于访问任何服务器都会造成压力，这是我想要规避的，尤其是我自己曾经在这方面投入并损失巨大。不过我尊重仓库作者自身意志。

> 我不太能接受自己打包，这样就不是官方的东西了，怕有人胡思乱想（即使编译文件一致）

您的顾虑很有道理，这一点是我没想到的，虽然我并不认为目前MC的材质包结构能造成什么攻击，或者重新打包的行为违反什么协议，但确实耐不住有人乱想乱说。

**Comment by zkitefly** [comment]
在之前我也是有考虑到这样的，所以用校验 index.html 的方式来检查更新，然后没糖说不用那么频繁，所以我就把他设置成凌晨 3 4 5 点

谢谢你的反馈
